namespace AcuPower.CustomizationTools.Builder.Items
{
    /// <summary>
    /// Helper for generating PerTenantFile (Modern UI) XML elements.
    /// </summary>
    public static class PerTenantFileItem
    {
        /// <summary>
        /// Returns an XML element string for a per-tenant file entry.
        /// </summary>
        /// <param name="appRelativePath">Application-relative path (e.g. "screens\AW\AW501000\AW501000.ts").</param>
        /// <param name="screenId">Screen ID (e.g. "AW501000").</param>
        public static string ToXml(string appRelativePath, string screenId)
        {
            return $"<PerTenantFile AppRelativePath=\"{EscapeXml(appRelativePath)}\" " +
                   $"ScreenId=\"{EscapeXml(screenId)}\" AutoGenerated=\"True\" />";
        }

        private static string EscapeXml(string value)
        {
            if (value == null) return string.Empty;
            return value
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;")
                .Replace("'", "&apos;");
        }
    }
}
